### ISSUE TITLE
Android Wear support

### ISSUE THREAD

**Issue by hotchemi** [kazz187/animetick-android#2]
It is definitely awesome if animetick-android supports android wear.
- Can check anime status from wear.
-  Notify when anime start.

**Comment by kazz187** [comment]
かっこいい！

**Comment by hotchemi** [comment]
Yep! I'll try it in my repository.

**Comment by kazz187** [comment]
Thanks. I expect your commits.
I wanna buy any android wear gadget. :smiley:
